version: "3.8"

services:

  pet-profile-service:
    build: ./pet-profile-service
    container_name: pet-profile-service
    ports:
      - "8081:8081"
    networks:
      - petnet

  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - "8082:8082"
    environment:
      - PET_SERVICE_URL=http://pet-profile-service:8081
    depends_on:
      - pet-profile-service
      - rabbitmq
    networks:
      - petnet

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8083:8083"
    depends_on:
      - rabbitmq
    networks:
      - petnet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - petnet

networks:
  petnet:
